--- FAIL: TestGetPrefix (0.00s)
panic: runtime error: slice bounds out of range [:5] with length 4 [recovered]
	panic: runtime error: slice bounds out of range [:5] with length 4

goroutine 7 [running]:
testing.tRunner.func1.2({0x5cd2a0, 0xc0000162d0})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x5cd2a0, 0xc0000162d0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
_/sandbox.getPrefix(...)
	/sandbox/main.go:27
_/sandbox.TestGetPrefix(0x0?)
	/sandbox/main_test.go:39 +0x216
testing.tRunner(0xc0001056c0, 0x5f1990)
	/usr/local/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1486 +0x35f
exit status 2
FAIL	_/sandbox	0.005s
